name: bookcrossing_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auth0_flutter: ^1.14.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  json_serializable: ^6.11.1
  test: ^1.26.2
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
